language: go
go_import_path: github.com/osbkit/minibroker
go:
- 1.10.x
sudo: required
services:
- docker
script:
- make build verify test-unit
deploy:
  provider: script
  script: make release
  on:
    repo: osbkit/minibroker
    all_branches: true
