language: go
go: 1.14.x

os: linux
dist: bionic

# Don't indent any line more than one level to avoid '\n' characters in the converter string,
# which breaks the regex free-spacing modifier. Also, do NOT include comments in the regex string.
if: >-
  ((branch = master) AND (tag IS NOT present))
  OR (
  (repo = "kubernetes-sigs/minibroker")
  AND (tag IS present)
  AND (branch ~= /^(?x)
  v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)
  (?:-((?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?
  (?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?
  $/)
  )

cache:
  directories:
  - ${HOME}/assets
  - ${GOPATH}/pkg/mod
  - ${GOPATH}/bin

jobs:
  include:
  - name: Verify
    stage: verify
    script: make verify
  - name: Lint
    stage: lint
    before_script:
    - GO111MODULE=on go install github.com/golang/mock/mockgen
    script: make lint
  - name: Test
    stage: test
    before_script:
    - go install github.com/onsi/ginkgo/ginkgo
    script: make test-unit
  - name: Integration tests
    stage: test-integration
    services:
    - docker
    env:
    - CHANGE_MINIKUBE_NONE_USER=false
    - MINIKUBE_HOME=${HOME}
    - TEST_PROVISION_TIMEOUT=5m
    - TEST_BIND_TIMEOUT=5m
    - TEST_ASSERT_TIMEOUT=2m
    # Forces the version.sh script to fetch tags and unshallow the git repository.
    - VERSION_FORCE_TAG_FETCH=true
    before_install:
    - sudo apt-get -qq -y install conntrack
    before_script:
    - ci/install/integration.sh
    - go install github.com/onsi/ginkgo/ginkgo
    script: ci/test_integration.sh
  - name: Release
    stage: release
    services:
    - docker
    env:
    # Forces the version.sh script to fetch tags and unshallow the git repository.
    - VERSION_FORCE_TAG_FETCH=true
    before_script:
    - ci/install/release.sh
    script: ci/release.sh

stages:
- verify
- lint
- test
- test-integration
- name: release
  if: (repo = "kubernetes-sigs/minibroker") AND (tag IS present) AND (branch != master)
