[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "k8s.io/helm"
  version = "2.8.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.2"

[[constraint]]
  name = "github.com/pmorie/osb-broker-lib"
  version = "0.0.10"
