required = [
  "github.com/kubernetes/repo-infra/tools/build_tar",
]

[[constraint]]
  name = "k8s.io/helm"
  version = "2.13.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.7.2"

[[constraint]]
  name = "github.com/pmorie/osb-broker-lib"
  version = "0.0.10"

[[constraint]]
  branch = "update-boilerplate"
  name = "github.com/kubernetes/repo-infra"
  source = "github.com/pivotal-k8s/repo-infra"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[prune.project]]
  name = "github.com/kubernetes/repo-infra"
  non-go = false
  unused-packages = false

