# Default values for the minibroker
# Image to use
image: osbkit/minibroker:latest
# ImagePullPolicy; valid values are "IfNotPresent", "Never", and "Always"
imagePullPolicy: IfNotPresent
deploymentPolicy: RollingUpdate
# Certificate details to use for TLS. Leave blank to not use TLS
tls:
  # base-64 encoded PEM data for the TLS certificate
  cert:
  # base-64 encoded PEM data for the private key matching the certificate
  key:

serviceCatalogEnabledOnly: true
