kind: Service
apiVersion: v1
metadata:
  name: {{ template "minibroker.fullname" . }}
  labels:
    {{- include "minibroker.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ template "minibroker.fullname" . }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.broker.deployment.port }}
