apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: {{ template "fullname" . }}-mysql-binding
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  instanceRef:
    name: {{ template "fullname" . }}-mysql-instance
  secretName: {{ template "fullname" . }}-mysql-secret
